[mypy]
python_version = 3.12
ignore_missing_imports = true
follow_imports = silent
disable_error_code =
    attr-defined,
    arg-type,
    assignment,
    call-arg,
    call-overload,
    list-item,
    misc,
    name-defined,
    no-any-return,
    no-untyped-call,
    no-untyped-def,
    operator,
    return-value,
    type-arg,
    untyped-decorator,
    var-annotated

[mypy-services.*]
strict = true

[mypy-repositories.*]
strict = true

[mypy-models.*]
strict = true
